version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/wasm"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "/packages/dart"
    schedule:
      interval: "monthly"
